/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.osoba;

import communication.Communication;
import domain.KategorijaOsobe;
import domain.Osoba;
import javax.swing.JOptionPane;
import transfer.Response;
import transfer.ResponseStatus;

/**
 *
 * @author PC
 */
public class IzmeniOsobu extends javax.swing.JFrame {

    /**
     * Creates new form IzmeniOsobu
     */
    
    Osoba izabrana; 
    
    public IzmeniOsobu(Osoba osoba) {
        initComponents();
        setLocationRelativeTo(this);
        this.izabrana = osoba;
        pripremiComboBox();
        popuniFormu();
    }

    private void pripremiComboBox() {
        cmbKategorija.removeAllItems();
        cmbKategorija.addItem("Standard");
        cmbKategorija.addItem("Student");
        cmbKategorija.addItem("Premium");
    }

    private void popuniFormu() {
        txtIme.setText(izabrana.getIme());
        txtPrezime.setText(izabrana.getPrezime());
        txtEmail.setText(izabrana.getEmail());
        txtTelefon.setText(izabrana.getTelefon());

        if (izabrana.getKategorijaOsobe() != null) {
            cmbKategorija.setSelectedItem(izabrana.getKategorijaOsobe().getNaziv());
        }
    }

    private void validirajFormu() throws Exception {
        if (txtIme.getText().trim().isEmpty()) {
            throw new Exception("Ime je obavezno.");
        }
        if (txtPrezime.getText().trim().isEmpty()) {
            throw new Exception("Prezime je obavezno.");
        }
        if (txtEmail.getText().trim().isEmpty()) {
            throw new Exception("Email je obavezan.");
        }
        if (txtTelefon.getText().trim().isEmpty()) {
            throw new Exception("Telefon je obavezan.");
        }
        if (cmbKategorija.getSelectedItem() == null) {
            throw new Exception("Kategorija je obavezna.");
        }
    }

    private KategorijaOsobe vratiKategorijuIzComboboxa() throws Exception {
        String naziv = (String) cmbKategorija.getSelectedItem();

        switch (naziv) {
            case "Standard":
                return new KategorijaOsobe(1L, "Standard");
            case "Student":
                return new KategorijaOsobe(2L, "Student");
            case "Premium":
                return new KategorijaOsobe(3L, "Premium");
            default:
                throw new Exception("Nepoznata kategorija.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTelefon = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbKategorija = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma Izmeni Osobu");

        btnIzmeni.setText("Izmeni osobu");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime: ");

        jLabel3.setText("Email:");

        jLabel4.setText("Telefon:");

        jLabel5.setText("Kategorija: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIzmeni)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIme)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbKategorija, javax.swing.GroupLayout.Alignment.TRAILING, 0, 228, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzmeni)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
         try {
        validirajFormu();

        izabrana.setIme(txtIme.getText().trim());
        izabrana.setPrezime(txtPrezime.getText().trim());
        izabrana.setEmail(txtEmail.getText().trim());
        izabrana.setTelefon(txtTelefon.getText().trim());
        izabrana.setKategorijaOsobe(vratiKategorijuIzComboboxa());

        Response response = Communication.getInstance().promeniOsobu(izabrana);

        if (response.getStatus() == ResponseStatus.SUCCESS) {
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio osobu.");
            this.dispose();
        } else {
            throw response.getException();
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti osobu.\n" + ex.getMessage());
    }

    }//GEN-LAST:event_btnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox cmbKategorija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

}
