/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Administrator;

/**
 *
 * @author PC
 */
public class FrmClanarinaProduzenjePaketa extends javax.swing.JFrame {

    /**
     * Creates new form FrmClanarinaProduzenjePaketa
     */
    private final domain.Administrator admin; // ako ti treba za title, nije obavezno
    private domain.Clanarina aktivna;         // trenutno učitana aktivna članarina

    private static final java.text.SimpleDateFormat SDF
            = new java.text.SimpleDateFormat("dd.MM.yyyy");

    public FrmClanarinaProduzenjePaketa(Administrator admin) {
        initComponents();
        this.admin = admin;

        SDF.setLenient(false);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        ucitajClanoveUCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbClanovi = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTrenutniDatumIsteka = new javax.swing.JTextField();
        txtNoviDatumIsteka = new javax.swing.JTextField();
        btnProduzi = new javax.swing.JButton();
        btnUcitaj = new javax.swing.JButton();
        btnIzracunaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produzenje Članarine");

        jLabel1.setText("Član:");

        cmbClanovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Trenutni datum isteka:");

        jLabel3.setText("Novi datum isteka:");

        txtTrenutniDatumIsteka.setEnabled(false);

        txtNoviDatumIsteka.setEnabled(false);

        btnProduzi.setText("Produzi");
        btnProduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduziActionPerformed(evt);
            }
        });

        btnUcitaj.setText("Ucitaj");
        btnUcitaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajActionPerformed(evt);
            }
        });

        btnIzracunaj.setText("Izracunaj");
        btnIzracunaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbClanovi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTrenutniDatumIsteka)
                            .addComponent(txtNoviDatumIsteka)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUcitaj)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzracunaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(btnProduzi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbClanovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTrenutniDatumIsteka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNoviDatumIsteka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduzi)
                    .addComponent(btnUcitaj)
                    .addComponent(btnIzracunaj))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUcitajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajActionPerformed
        try {
            domain.Clan c = (domain.Clan) cmbClanovi.getSelectedItem();
            if (c == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Izaberi člana.");
                return;
            }

            transfer.Response res = communication.Communication.getInstance().send(
                    new transfer.Request(
                            transfer.enums.RequestType.PRONADJI_AKTIVNU_CLANARINU_ZA_CLANA,
                            Integer.valueOf(c.getClanID())
                    )
            );

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            aktivna = (domain.Clanarina) res.getResult();

            if (aktivna == null) {
                txtTrenutniDatumIsteka.setText("");
                txtNoviDatumIsteka.setText("");
                javax.swing.JOptionPane.showMessageDialog(this, "Član nema aktivnu članarinu.");
                return;
            }

            // Prikaz trenutnog isteka
            txtTrenutniDatumIsteka.setText(SDF.format(aktivna.getDatumIsteka()));
            txtNoviDatumIsteka.setText("");

            // Ako server vraća i trajanjeDana u aktivna.getPaket().getTrajanjeDana(),
            // možemo odmah izračunati novi datum:
            izracunajNoviIstek();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Greška", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUcitajActionPerformed

    private void btnProduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduziActionPerformed
        try {
            domain.Clan c = (domain.Clan) cmbClanovi.getSelectedItem();
            if (c == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Izaberi člana.");
                return;
            }

            if (aktivna == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Prvo učitaj aktivnu članarinu.");
                return;
            }

            String noviText = txtNoviDatumIsteka.getText().trim();
            if (noviText.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Novi datum isteka nije izračunat.");
                return;
            }

            java.util.Date noviUtil;
            try {
                noviUtil = SDF.parse(noviText);
            } catch (java.text.ParseException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Novi datum mora biti u formatu dd.MM.yyyy");
                return;
            }

            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "Produži članarinu do: " + noviText + " ?",
                    "Potvrda produženja",
                    javax.swing.JOptionPane.YES_NO_OPTION
            );
            if (confirm != javax.swing.JOptionPane.YES_OPTION) {
                return;
            }

            transfer.ProduziPaketRequest pr = new transfer.ProduziPaketRequest(
                    c.getClanID(),
                    new java.sql.Date(noviUtil.getTime())
            );

            transfer.Response res = communication.Communication.getInstance().send(
                    new transfer.Request(transfer.enums.RequestType.PRODUZI_PAKET_CLANU, pr)
            );

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Članarina je produžena.");

            // osveži prikaz
            btnUcitajActionPerformed(null);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Greška", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }    }//GEN-LAST:event_btnProduziActionPerformed

    private void btnIzracunajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunajActionPerformed
        try {
            if (aktivna == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Prvo učitaj aktivnu članarinu.");
                return;
            }
            izracunajNoviIstek();
            if (txtNoviDatumIsteka.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Nije moguće izračunati novi istek (nema trajanja paketa).");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }    }//GEN-LAST:event_btnIzracunajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzracunaj;
    private javax.swing.JButton btnProduzi;
    private javax.swing.JButton btnUcitaj;
    private javax.swing.JComboBox cmbClanovi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNoviDatumIsteka;
    private javax.swing.JTextField txtTrenutniDatumIsteka;
    // End of variables declaration//GEN-END:variables

    private void ucitajClanoveUCombo() {
        try {
            transfer.Response res = communication.Communication.getInstance().send(
                    new transfer.Request(transfer.enums.RequestType.VRATI_LISTU_CLANOVA, null)
            );

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            java.util.List<domain.Clan> list = (java.util.List<domain.Clan>) res.getResult();

            cmbClanovi.removeAllItems();
            for (domain.Clan c : list) {
                cmbClanovi.addItem(c);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    private void izracunajNoviIstek() throws Exception {
        if (aktivna == null) {
            return;
        }

        int trajanje = aktivna.getPaket() != null ? aktivna.getPaket().getTrajanjeDana() : 0;
        if (trajanje <= 0) {
            // Ako nema trajanjeDana, ne možemo računati na klijentu
            // (u tom slučaju ili dodaj JOIN na serveru ili u UI traži unos novog datuma)
            return;
        }

        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.setTime(aktivna.getDatumIsteka());
        cal.add(java.util.Calendar.DAY_OF_MONTH, trajanje);

        java.util.Date novi = cal.getTime();
        txtNoviDatumIsteka.setText(SDF.format(novi));
    }
}
