/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Administrator;

/**
 *
 * @author PC
 */
public class FrmClanarinaKreiraj extends javax.swing.JFrame {

    /**
     * Creates new form FrmClanarinaKreiraj
     */
    private final Administrator admin;

    private static final java.text.SimpleDateFormat SDF
            = new java.text.SimpleDateFormat("dd.MM.yyyy");

    public FrmClanarinaKreiraj(Administrator admin) {
        initComponents();
        this.admin = admin;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(this);

        ucitajClanoveUCombo();
        ucitajPaketeUCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDodeli = new javax.swing.JButton();
        cmbClan = new javax.swing.JComboBox();
        cmbPaket = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtDatumPocetka = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kreiraj Članarinu");

        jLabel1.setText("Član:");

        jLabel2.setText("Paket:");

        btnDodeli.setText("Dodeli");
        btnDodeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodeliActionPerformed(evt);
            }
        });

        cmbClan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPaket.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Datum početka:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDodeli))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPaket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbClan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumPocetka, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDodeli)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodeliActionPerformed
        try {
            domain.Clan c = (domain.Clan) cmbClan.getSelectedItem();
            domain.Paket p = (domain.Paket) cmbPaket.getSelectedItem();

            if (c == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Izaberi člana.");
                return;
            }
            if (p == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Izaberi paket.");
                return;
            }

            String startText = txtDatumPocetka.getText().trim();
            if (startText.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Unesi datum početka (dd.MM.yyyy).");
                return;
            }

            java.util.Date utilStart;
            try {
                SDF.setLenient(false);
                utilStart = SDF.parse(startText);

                java.util.Date today = new java.util.Date();

                java.util.Calendar calToday = java.util.Calendar.getInstance();
                calToday.setTime(today);
                calToday.set(java.util.Calendar.HOUR_OF_DAY, 0);
                calToday.set(java.util.Calendar.MINUTE, 0);
                calToday.set(java.util.Calendar.SECOND, 0);
                calToday.set(java.util.Calendar.MILLISECOND, 0);

                java.util.Date todayWithoutTime = calToday.getTime();

                if (!utilStart.after(todayWithoutTime)) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Datum početka mora biti posle današnjeg datuma.");
                    return;
                }
            } catch (java.text.ParseException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Datum mora biti u formatu dd.MM.yyyy.");
                return;
            }

            domain.Clanarina cl = new domain.Clanarina();
            cl.setClan(c);
            cl.setPaket(p);
            cl.setDatumPocetka(new java.sql.Date(utilStart.getTime()));
            // datumIsteka i status NE računa klijent

            transfer.Response res = communication.Communication.getInstance().send(
                    new transfer.Request(transfer.enums.RequestType.DODELI_PAKET_CLANU, cl)
            );

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Paket je dodeljen članu.");
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Greška", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDodeliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodeli;
    private javax.swing.JComboBox cmbClan;
    private javax.swing.JComboBox cmbPaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDatumPocetka;
    // End of variables declaration//GEN-END:variables

    private void ucitajClanoveUCombo() {
        try {
            transfer.Request req = new transfer.Request(
                    transfer.enums.RequestType.VRATI_LISTU_CLANOVA, null);

            transfer.Response res = communication.Communication.getInstance().send(req);

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            java.util.List<domain.Clan> list
                    = (java.util.List<domain.Clan>) res.getResult();

            cmbClan.removeAllItems();
            for (domain.Clan c : list) {
                cmbClan.addItem(c);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    private void ucitajPaketeUCombo() {
        try {
            transfer.Request req = new transfer.Request(
                    transfer.enums.RequestType.VRATI_LISTU_PAKETA, null);

            transfer.Response res = communication.Communication.getInstance().send(req);

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            java.util.List<domain.Paket> list
                    = (java.util.List<domain.Paket>) res.getResult();

            cmbPaket.removeAllItems();
            for (domain.Paket p : list) {
                cmbPaket.addItem(p);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }
}
