/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Administrator;

/**
 * *
 *
 * @author PC
 */
public class FrmClanoviIzmeni extends javax.swing.JFrame {

    private final Administrator admin;

    /**
     * Creates new form FrmIzmeniClana
     */
    public FrmClanoviIzmeni(Administrator admin) {
        initComponents();
        this.admin = admin;

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        ucitajClanoveUCombo();
        // Kad se učita lista, možemo automatski popuniti polja za prvog
        if (cmbClan.getItemCount() > 0) {
            cmbClan.setSelectedIndex(0);
            popuniPoljaIzSelektovanog();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void popuniPoljaIzSelektovanog() {
        try {
            domain.Clan c = (domain.Clan) cmbClan.getSelectedItem();
            if (c == null) {
                return;
            }

            txtIme.setText(c.getIme());
            txtPrezime.setText(c.getPrezime());
            txtEmail.setText(c.getEmail());
            txtTelefon.setText(c.getTelefon());
            chckboxAktivan.setSelected(c.isAktivan());

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Sistem ne može da učita člana.",
                    "Greška",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }

        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chckboxAktivan = new javax.swing.JCheckBox();
        btnIzmeni = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbClan = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Izmeni člana");

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("Email: ");

        jLabel4.setText("Telefon:");

        jLabel5.setText("Aktivan: ");

        btnIzmeni.setText("Izmeni člana");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel6.setText("Član:");

        cmbClan.setSelectedItem(null);
        cmbClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzmeni))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chckboxAktivan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbClan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chckboxAktivan))
                .addGap(18, 18, 18)
                .addComponent(btnIzmeni)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            domain.Clan selected = (domain.Clan) cmbClan.getSelectedItem();
            if (selected == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Izaberi člana.");
                return;
            }

            // napravimo objekat za update
            domain.Clan c = new domain.Clan();
            c.setClanID(selected.getClanID());
            c.setIme(txtIme.getText().trim());
            c.setPrezime(txtPrezime.getText().trim());
            c.setEmail(txtEmail.getText().trim());
            c.setTelefon(txtTelefon.getText().trim());
            c.setAktivan(chckboxAktivan.isSelected());

            // admin prosleđen kroz konstruktor (kako si hteo)
            domain.Administrator a = new domain.Administrator();
            a.setAdministratorID(admin.getAdministratorID());
            c.setAdministrator(a);

            transfer.Request req = new transfer.Request(
                    transfer.enums.RequestType.IZMENI_CLANA, c);

            transfer.Response res = communication.Communication.getInstance().send(req);

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Član je izmenjen.");

            // (opciono) osveži combo da povuče nove podatke iz baze:
            ucitajClanoveUCombo();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Greška", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void cmbClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClanActionPerformed
        popuniPoljaIzSelektovanog();
    }//GEN-LAST:event_cmbClanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JCheckBox chckboxAktivan;
    private javax.swing.JComboBox cmbClan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

    private void ucitajClanoveUCombo() {
        try {
            transfer.Request req = new transfer.Request(
                    transfer.enums.RequestType.VRATI_LISTU_CLANOVA, null);

            transfer.Response res = communication.Communication.getInstance().send(req);

            if (res == null || !res.isSuccessful()) {
                if (res != null && res.getException() != null) {
                    res.getException().printStackTrace();
                }
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Sistem ne može da pronađe članove po zadatoj vrednosti.",
                        "Greška",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            java.util.List<domain.Clan> list = (java.util.List<domain.Clan>) res.getResult();

            cmbClan.removeAllItems();
            for (domain.Clan c : list) {
                cmbClan.addItem(c);
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Sistem ne može da pronađe članove po zadatoj vrednosti.",
                    "Greška",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }
}
