/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Administrator;

/**
 *
 * @author PC
 */
public class FrmPaketi extends javax.swing.JFrame {

    /**
     * Creates new form FrmPaketi
     */
    
    private final Administrator admin;
    
    public FrmPaketi(Administrator admin) {
        initComponents();
        this.admin = admin;
         tblPaketi.setModel(new model.PaketTableModel());
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaketi = new javax.swing.JTable();
        btnUcitajPakete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paketi");

        tblPaketi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPaketi);

        btnUcitajPakete.setText("Ucitaj Pakete");
        btnUcitajPakete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajPaketeActionPerformed(evt);
            }
        });

        jLabel1.setText("Pretraga: ");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 746, Short.MAX_VALUE)
                        .addComponent(btnPretrazi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUcitajPakete)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUcitajPakete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUcitajPaketeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajPaketeActionPerformed
       ucitajListuPaketa();
    }//GEN-LAST:event_btnUcitajPaketeActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
       try {
            String q = txtPretraga.getText().trim();

            transfer.Request req = new transfer.Request(
                    transfer.enums.RequestType.PRONADJI_PAKETE, q
            );

            transfer.Response res = communication.Communication.getInstance().send(req);

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            java.util.List<domain.Paket> list
                    = (java.util.List<domain.Paket>) res.getResult();

            model.PaketTableModel m = (model.PaketTableModel) tblPaketi.getModel();
            m.setData(list);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_btnPretraziActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnUcitajPakete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPaketi;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void ucitajListuPaketa() {
 try {
            transfer.Request req
                    = new transfer.Request(transfer.enums.RequestType.VRATI_LISTU_PAKETA, null);

            transfer.Response res
                    = communication.Communication.getInstance().send(req);

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            java.util.List<domain.Paket> list
                    = (java.util.List<domain.Paket>) res.getResult();

            model.PaketTableModel m = (model.PaketTableModel) tblPaketi.getModel();
            m.setData(list);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }

    }
}
