/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Administrator;

/**
 *
 * @author PC
 */
public class FrmPaketKreiraj extends javax.swing.JFrame {

    /**
     * Creates new form FrmPaket
     */
    private final Administrator admin;

    public FrmPaketKreiraj(Administrator admin) {
        initComponents();
        this.admin = admin;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNazivPaketa = new javax.swing.JTextField();
        txtTrajanjeDana = new javax.swing.JTextField();
        txtCena = new javax.swing.JTextField();
        txtBrojDolazaka = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kreiraj Paket");

        jLabel1.setText("Naziv paketa: ");

        jLabel2.setText("Trajanje dana: ");

        jLabel3.setText("Cena: ");

        jLabel4.setText("Broj dolazaka:");

        jButton1.setText("Kreiraj Paket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTrajanjeDana, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtNazivPaketa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrojDolazaka)
                            .addComponent(txtCena))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNazivPaketa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTrajanjeDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBrojDolazaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String naziv = txtNazivPaketa.getText().trim();
            String trajanjeTekst = txtTrajanjeDana.getText().trim();
            String cenaTekst = txtCena.getText().trim();
            String brojDolazakaTekst = txtBrojDolazaka.getText().trim();

            if (naziv.isEmpty() || trajanjeTekst.isEmpty() || cenaTekst.isEmpty() || brojDolazakaTekst.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Sva polja su obavezna.");
                return;
            }

            int trajanjeDana;
            double cena;
            int brojDolazaka;

            try {
                trajanjeDana = Integer.parseInt(trajanjeTekst);
                cena = Double.parseDouble(cenaTekst);
                brojDolazaka = Integer.parseInt(brojDolazakaTekst);
            } catch (NumberFormatException nfe) {
                javax.swing.JOptionPane.showMessageDialog(this, "Greška! Trajanje, cena i broj dolazaka moraju biti brojevi.");
                return;
            }

            if (trajanjeDana <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, " Greška! Trajanje mora biti > 0.");
                return;
            }
            if (cena <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Greška! Cena mora biti > 0.");
                return;
            }
            if (brojDolazaka <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Greška! Broj dolazaka mora biti > 0.");
                return;
            }

            domain.Paket p = new domain.Paket();
            p.setNaziv(naziv);
            p.setTrajanjeDana(trajanjeDana);
            p.setCena(cena);
            p.setBrojDozvoljenihDolazaka(brojDolazaka);

            domain.Administrator a = new domain.Administrator();
            a.setAdministratorID(admin.getAdministratorID());
            p.setAdministrator(a);

            transfer.Request req = new transfer.Request(
                    transfer.enums.RequestType.SACUVAJ_PAKET, p
            );

            transfer.Response res = communication.Communication.getInstance().send(req);

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Paket je sačuvan.");
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Greška", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtBrojDolazaka;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtNazivPaketa;
    private javax.swing.JTextField txtTrajanjeDana;
    // End of variables declaration//GEN-END:variables
}
