/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Administrator;

/**
 *
 * @author PC
 */
public class FrmPaketIzmeni extends javax.swing.JFrame {

    /**
     * Creates new form FrmPaketIzmeni
     */
    private final Administrator admin;

    public FrmPaketIzmeni(Administrator admin) {
        initComponents();
        this.admin = admin;

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        ucitajPaketeUCombo();
        // Kad se učita lista, možemo automatski popuniti polja za prvog
        if (cmbPaketi.getItemCount() > 0) {
            cmbPaketi.setSelectedIndex(0);
            popuniPoljaIzSelektovanog();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbPaketi = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtNazivPaketa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTrajanjeDana = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBrojDolazaka = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Paket:");

        cmbPaketi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPaketi.setSelectedItem(null
        );
        cmbPaketi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaketiActionPerformed(evt);
            }
        });

        jLabel2.setText("Naziv paketa: ");

        jLabel3.setText("Trajanje dana: ");

        jLabel4.setText("Cena: ");

        jLabel5.setText("Broj dolazaka:");

        btnIzmeni.setText("Izmeni Paket");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPaketi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzmeni))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNazivPaketa, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(txtTrajanjeDana)
                            .addComponent(txtBrojDolazaka)
                            .addComponent(txtCena))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPaketi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivPaketa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTrajanjeDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBrojDolazaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(btnIzmeni)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            domain.Paket selected = (domain.Paket) cmbPaketi.getSelectedItem();
            if (selected == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Izaberi paket.");
                return;
            }

            String naziv = txtNazivPaketa.getText().trim();
            String trajanjeTekst = txtTrajanjeDana.getText().trim();
            String cenaTekst = txtCena.getText().trim();
            String brojDolazakaTekst = txtBrojDolazaka.getText().trim();

            if (naziv.isEmpty() || trajanjeTekst.isEmpty() || cenaTekst.isEmpty() || brojDolazakaTekst.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Sva polja su obavezna.");
                return;
            }

            int trajanjeDana;
            double cena;
            int brojDolazaka;

            try {
                trajanjeDana = Integer.parseInt(trajanjeTekst);
                cena = Double.parseDouble(cenaTekst);
                brojDolazaka = Integer.parseInt(brojDolazakaTekst);
            } catch (NumberFormatException nfe) {
                javax.swing.JOptionPane.showMessageDialog(this, "Trajanje, cena i broj dolazaka moraju biti brojevi.");
                return;
            }

            if (trajanjeDana <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Trajanje mora biti > 0.");
                return;
            }
            if (cena <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cena mora biti > 0.");
                return;
            }
            if (brojDolazaka <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Broj dolazaka mora biti > 0.");
                return;
            }

            // objekat za update
            domain.Paket p = new domain.Paket();
            p.setPaketID(selected.getPaketID());
            p.setNaziv(naziv);
            p.setTrajanjeDana(trajanjeDana);
            p.setCena(cena);
            p.setBrojDozvoljenihDolazaka(brojDolazaka);

            // admin prosleđen kroz konstruktor
            domain.Administrator a = new domain.Administrator();
            a.setAdministratorID(admin.getAdministratorID());
            p.setAdministrator(a);

            transfer.Request req = new transfer.Request(
                    transfer.enums.RequestType.IZMENI_PAKET, p
            );

            transfer.Response res = communication.Communication.getInstance().send(req);

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Paket je izmenjen.");

            // osveži combo da povuče nove podatke iz baze
            ucitajPaketeUCombo();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Greška", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void cmbPaketiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaketiActionPerformed
        popuniPoljaIzSelektovanog();

    }//GEN-LAST:event_cmbPaketiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox cmbPaketi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtBrojDolazaka;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtNazivPaketa;
    private javax.swing.JTextField txtTrajanjeDana;
    // End of variables declaration//GEN-END:variables

    private void ucitajPaketeUCombo() {
        try {
            transfer.Request req = new transfer.Request(
                    transfer.enums.RequestType.VRATI_LISTU_PAKETA, null);

            transfer.Response res = communication.Communication.getInstance().send(req);

            if (!res.isSuccessful()) {
                throw res.getException();
            }

            java.util.List<domain.Paket> list
                    = (java.util.List<domain.Paket>) res.getResult();

            cmbPaketi.removeAllItems();
            for (domain.Paket p : list) {
                cmbPaketi.addItem(p);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }

    }

    private void popuniPoljaIzSelektovanog() {
        domain.Paket p = (domain.Paket) cmbPaketi.getSelectedItem();
        if (p == null) {
            return;
        }

        txtNazivPaketa.setText(p.getNaziv());
        txtTrajanjeDana.setText(Integer.toString(p.getTrajanjeDana()));
        txtCena.setText(Double.toString(p.getCena()));
        txtBrojDolazaka.setText(Integer.toString(p.getBrojDozvoljenihDolazaka()));

    }
}
