/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.videoIgre;

import communication.Communication;
import domain.VideoIgra;
import javax.swing.JOptionPane;
import transfer.Response;
import transfer.ResponseStatus;

/**
 *
 * @author PC
 */
public class IzmeniVideoIgru extends javax.swing.JFrame {

    private VideoIgra videoIgra;

    public IzmeniVideoIgru(VideoIgra videoIgra) {
        initComponents();
        setLocationRelativeTo(this);
        this.videoIgra = videoIgra;
        popuniFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCena = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtZanr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPlatforma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma Izmeni Video Igru");

        jLabel3.setText("Cena:");

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane2.setViewportView(txtOpis);

        jLabel4.setText("Opis:");

        jLabel5.setText("Platforma: ");

        jLabel1.setText("Naziv: ");

        jLabel2.setText("Žanr:");

        btnIzmeni.setText("Izmeni video igru");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNaziv)
                    .addComponent(txtZanr)
                    .addComponent(txtPlatforma)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzmeni)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPlatforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(btnIzmeni)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
 try {
        validirajFormu();

        videoIgra.setNaziv(txtNaziv.getText().trim());
        videoIgra.setZanr(txtZanr.getText().trim());
        videoIgra.setPlatforma(txtPlatforma.getText().trim());
        videoIgra.setCenaIznajmljivanja(Double.parseDouble(txtCena.getText().trim()));
        videoIgra.setOpis(txtOpis.getText().trim());

        Response response = Communication.getInstance().promeniVideoIgru(videoIgra);

        if (response.getStatus() == ResponseStatus.SUCCESS) {
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio video igru.");
            dispose();
        } else {
            throw response.getException();
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti video igru.\n" + ex.getMessage());
    }    }//GEN-LAST:event_btnIzmeniActionPerformed

   private void validirajFormu() throws Exception {
    if (txtNaziv.getText().trim().isEmpty()) {
        throw new Exception("Naziv je obavezan.");
    }

    if (txtZanr.getText().trim().isEmpty()) {
        throw new Exception("Žanr je obavezan.");
    }

    if (txtPlatforma.getText().trim().isEmpty()) {
        throw new Exception("Platforma je obavezna.");
    }

    if (txtCena.getText().trim().isEmpty()) {
        throw new Exception("Cena je obavezna.");
    }

    try {
        double cena = Double.parseDouble(txtCena.getText().trim());
        if (cena <= 0) {
            throw new Exception("Cena mora biti veća od 0.");
        }
    } catch (NumberFormatException e) {
        throw new Exception("Cena mora biti broj.");
    }
}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtPlatforma;
    private javax.swing.JTextField txtZanr;
    // End of variables declaration//GEN-END:variables

    private void popuniFormu() {
        txtNaziv.setText(videoIgra.getNaziv());
        txtZanr.setText(videoIgra.getZanr());
        txtPlatforma.setText(videoIgra.getPlatforma());
        txtCena.setText(String.valueOf(videoIgra.getCenaIznajmljivanja()));
        txtOpis.setText(videoIgra.getOpis());
    }
}
