/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.videoIgre;

import communication.Communication;
import domain.VideoIgra;
import javax.swing.JOptionPane;
import models.ModelTabeleVideoIgre;
import transfer.Response;
import transfer.ResponseStatus;

/**
 *
 * @author PC
 */
public class KreirajVideoIgre extends javax.swing.JFrame {

    /**
     * Creates new form KreirajVideoIgre
     */
    public KreirajVideoIgre() {
        initComponents();
        setLocationRelativeTo(this);
        tblVideoIgre.setModel(new ModelTabeleVideoIgre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVideoIgre = new javax.swing.JTable();
        btnKreirajVideoIgre = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        txtNaziv = new javax.swing.JTextField();
        txtZanr = new javax.swing.JTextField();
        txtPlatforma = new javax.swing.JTextField();
        txtCena = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma Kreiraj Video Igre");

        jLabel1.setText("Naziv: ");

        jLabel2.setText("Žanr:");

        jLabel3.setText("Cena:");

        jLabel4.setText("Opis:");

        jLabel5.setText("Platforma: ");

        tblVideoIgre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVideoIgre);

        btnKreirajVideoIgre.setText("Kreiraj video igre");
        btnKreirajVideoIgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajVideoIgreActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj video igru");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane2.setViewportView(txtOpis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNaziv)
                            .addComponent(txtZanr)
                            .addComponent(txtPlatforma)
                            .addComponent(txtCena, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDodaj)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 111, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKreirajVideoIgre)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPlatforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDodaj)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKreirajVideoIgre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajVideoIgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajVideoIgreActionPerformed
        try {
            ModelTabeleVideoIgre model = (ModelTabeleVideoIgre) tblVideoIgre.getModel();

            if (model.getLista().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti video igru.");
                return;
            }

            for (VideoIgra vi : model.getLista()) {
                Response response = Communication.getInstance().kreirajVideoIgru(vi);

                if (response.getStatus() == ResponseStatus.ERROR) {
                    throw response.getException();
                }
            }

            JOptionPane.showMessageDialog(this, "Sistem je zapamtio video igre.");

            model.setLista(new java.util.ArrayList<>());
            ocistiPolja();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti video igre.\n" + ex.getMessage());
        }
    }//GEN-LAST:event_btnKreirajVideoIgreActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try {
            validirajUnos();

            String naziv = txtNaziv.getText().trim();
            String zanr = txtZanr.getText().trim();
            String platforma = txtPlatforma.getText().trim();
            double cena = Double.parseDouble(txtCena.getText().trim());
            String opis = txtOpis.getText().trim();

            VideoIgra vi = new VideoIgra(null, naziv, zanr, platforma, cena, opis);

            ModelTabeleVideoIgre model = (ModelTabeleVideoIgre) tblVideoIgre.getModel();
            model.dodajVideoIgru(vi);

            JOptionPane.showMessageDialog(this, "Igra je dodata u tabelu.");

            ocistiPolja();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }    }//GEN-LAST:event_btnDodajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnKreirajVideoIgre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVideoIgre;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtPlatforma;
    private javax.swing.JTextField txtZanr;
    // End of variables declaration//GEN-END:variables

    private void ocistiPolja() {
        txtNaziv.setText("");
        txtZanr.setText("");
        txtPlatforma.setText("");
        txtCena.setText("");
        txtOpis.setText("");
    }

    private void validirajUnos() throws Exception {
        if (txtNaziv.getText().trim().isEmpty()) {
            throw new Exception("Naziv je obavezan.");
        }

        if (txtZanr.getText().trim().isEmpty()) {
            throw new Exception("Žanr je obavezan.");
        }

        if (txtPlatforma.getText().trim().isEmpty()) {
            throw new Exception("Platforma je obavezna.");
        }

        if (txtCena.getText().trim().isEmpty()) {
            throw new Exception("Cena je obavezna.");
        }

        try {
            double cena = Double.parseDouble(txtCena.getText().trim());
            if (cena <= 0) {
                throw new Exception("Cena mora biti veća od 0.");
            }
        } catch (NumberFormatException e) {
            throw new Exception("Cena mora biti broj.");
        }
    }
}
