/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import communication.Communication;
import domain.Iznajmljivanje;
import domain.Osoba;
import domain.StavkaIznajmljivanja;
import domain.VideoIgra;
import domain.Zaposleni;
import form.iznajmljivanje.IzmeniIznajmljivanje;
import form.iznajmljivanje.KreirajIznajmljivanje;
import java.util.List;
import javax.swing.JOptionPane;
import models.ModelTabeleIznajmljivanje;
import transfer.Response;
import transfer.ResponseStatus;

/**
 *
 * @author PC
 */
public class FrmIznajmljivanje extends javax.swing.JFrame {

    /**
     * Creates new form FrmIznajmljivanje
     */
    Zaposleni admin;

    public FrmIznajmljivanje(Zaposleni ulogovani) {
        initComponents();
        this.admin = ulogovani;
        setLocationRelativeTo(this);
        srediTabelu();
        pripremiFormu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblIznajmljivanje = new javax.swing.JTable();
        btnUcitajIznajmljivanje = new javax.swing.JButton();
        btnKreirajIznajmljivanje = new javax.swing.JButton();
        btnIzmeniIznajmljivanje = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdIznajmljivanje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbZaposleni = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbVideoIgra = new javax.swing.JComboBox();
        cmbOsoba = new javax.swing.JComboBox();
        btnPretraziIznajmljivanje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma Iznajmljivanje");
        setAlwaysOnTop(true);

        tblIznajmljivanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIznajmljivanje);

        btnUcitajIznajmljivanje.setText("Ucitaj iznajmljivanja");
        btnUcitajIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajIznajmljivanjeActionPerformed(evt);
            }
        });

        btnKreirajIznajmljivanje.setText("Kreiraj iznajmljivanje");
        btnKreirajIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajIznajmljivanjeActionPerformed(evt);
            }
        });

        btnIzmeniIznajmljivanje.setText("Izmeni iznajmljivanje");
        btnIzmeniIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniIznajmljivanjeActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        jLabel1.setText("Kriterijum: ");

        jLabel2.setText("Zaposleni: ");

        cmbZaposleni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Osoba: ");

        jLabel4.setText("Video igra: ");

        cmbVideoIgra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbOsoba.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPretraziIznajmljivanje.setText("Pretrazi");
        btnPretraziIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziIznajmljivanjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdIznajmljivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbOsoba, 0, 158, Short.MAX_VALUE)
                            .addComponent(cmbVideoIgra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKreirajIznajmljivanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUcitajIznajmljivanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeniIznajmljivanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNazad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPretraziIznajmljivanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdIznajmljivanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cmbOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cmbVideoIgra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPretraziIznajmljivanje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUcitajIznajmljivanje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKreirajIznajmljivanje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeniIznajmljivanje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNazad))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUcitajIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajIznajmljivanjeActionPerformed

        ucitajIznajmljivanja();

    }//GEN-LAST:event_btnUcitajIznajmljivanjeActionPerformed

    private void btnKreirajIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajIznajmljivanjeActionPerformed

        try {
            KreirajIznajmljivanje forma = new KreirajIznajmljivanje(admin);
            forma.setVisible(true);

            ucitajIznajmljivanja();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri otvaranju forme za kreiranje.\n" + ex.getMessage());
        }

    }//GEN-LAST:event_btnKreirajIznajmljivanjeActionPerformed

    private void btnIzmeniIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniIznajmljivanjeActionPerformed
        try {
            int selectedRow = tblIznajmljivanje.getSelectedRow();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe iznajmljivanje.");
                return;
            }

            ModelTabeleIznajmljivanje model = (ModelTabeleIznajmljivanje) tblIznajmljivanje.getModel();
            Iznajmljivanje i = model.vratiIznajmljivanje(selectedRow);

            List<StavkaIznajmljivanja> stavke
                    = Communication.getInstance().ucitajStavkeIznajmljivanja(i);

            i.setStavke(stavke);

            IzmeniIznajmljivanje forma = new IzmeniIznajmljivanje(admin, i);
            forma.setLocationRelativeTo(this);
            forma.setVisible(true);

            ucitajIznajmljivanja();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri otvaranju forme: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnIzmeniIznajmljivanjeActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnPretraziIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziIznajmljivanjeActionPerformed
        try {
            Iznajmljivanje kriterijum = new Iznajmljivanje();

            String txtId = txtIdIznajmljivanje.getText().trim();
            if (!txtId.isEmpty()) {
                kriterijum.setIdIznajmljivanje(Long.parseLong(txtId));
            }

            Zaposleni z = (Zaposleni) cmbZaposleni.getSelectedItem();
            if (z != null && z.getIdZaposleni() != null) {
                kriterijum.setZaposleni(z);
            }

            Osoba o = (Osoba) cmbOsoba.getSelectedItem();
            if (o != null && o.getIdOsoba() != null) {
                kriterijum.setOsoba(o);
            }

            List<Iznajmljivanje> lista = Communication.getInstance().pretraziIznajmljivanja(kriterijum);

            VideoIgra vi = (VideoIgra) cmbVideoIgra.getSelectedItem();

            if (vi != null && vi.getIdVideoIgra() != null) {
                List<Iznajmljivanje> filtrirana = new java.util.ArrayList<>();

                for (Iznajmljivanje i : lista) {
                    List<StavkaIznajmljivanja> stavke
                            = Communication.getInstance().ucitajStavkeIznajmljivanja(i);

                    boolean pronadjena = false;

                    for (StavkaIznajmljivanja s : stavke) {
                        if (s.getVideoIgra() != null
                                && s.getVideoIgra().getIdVideoIgra() != null
                                && s.getVideoIgra().getIdVideoIgra().equals(vi.getIdVideoIgra())) {
                            pronadjena = true;
                            break;
                        }
                    }

                    if (pronadjena) {
                        filtrirana.add(i);
                    }
                }

                lista = filtrirana;
            }

            ModelTabeleIznajmljivanje model
                    = (ModelTabeleIznajmljivanje) tblIznajmljivanje.getModel();
            model.setLista(lista);

            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Sistem ne može da nađe iznajmljivanja po zadatim kriterijumima.");
            } else {
                JOptionPane.showMessageDialog(this,
                        "Sistem je našao iznajmljivanja po zadatim kriterijumima.");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnPretraziIznajmljivanjeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniIznajmljivanje;
    private javax.swing.JButton btnKreirajIznajmljivanje;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnPretraziIznajmljivanje;
    private javax.swing.JButton btnUcitajIznajmljivanje;
    private javax.swing.JComboBox cmbOsoba;
    private javax.swing.JComboBox cmbVideoIgra;
    private javax.swing.JComboBox cmbZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIznajmljivanje;
    private javax.swing.JTextField txtIdIznajmljivanje;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ModelTabeleIznajmljivanje mti = new ModelTabeleIznajmljivanje();
        tblIznajmljivanje.setModel(mti);
    }

    private void ucitajIznajmljivanja() {
        try {
            Response response = Communication.getInstance().ucitajIznajmljivanja();

            if (response.getStatus() == ResponseStatus.ERROR) {
                throw response.getException();
            }

            List<Iznajmljivanje> lista = (List<Iznajmljivanje>) response.getPodatak();

            ModelTabeleIznajmljivanje model = (ModelTabeleIznajmljivanje) tblIznajmljivanje.getModel();
            model.setLista(lista);

            JOptionPane.showMessageDialog(this, "Sistem je učitao iznajmljivanja.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita iznajmljivanja.\n" + ex.getMessage());
        }
    }

    private void pripremiFormu() {
        tblIznajmljivanje.setModel(new ModelTabeleIznajmljivanje());

        ucitajComboOsobe();
        ucitajComboVideoIgre();
        ucitajComboZaposleni();
    }

    private void ucitajComboOsobe() {
        try {
            Response response = Communication.getInstance().ucitajOsobe();

            if (response.getStatus() == ResponseStatus.ERROR) {
                throw response.getException();
            }

            List<Osoba> lista = (List<Osoba>) response.getPodatak();

            cmbOsoba.removeAllItems();

            Osoba sve = new Osoba();
            cmbOsoba.addItem(sve);

            for (Osoba o : lista) {
                cmbOsoba.addItem(o);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju osoba: " + ex.getMessage());
        }
    }

    private void ucitajComboVideoIgre() {
        try {
            Response response = Communication.getInstance().ucitajVideoIgre();

            if (response.getStatus() == ResponseStatus.ERROR) {
                throw response.getException();
            }

            List<VideoIgra> lista = (List<VideoIgra>) response.getPodatak();

            cmbVideoIgra.removeAllItems();

            VideoIgra sve = new VideoIgra();
            cmbVideoIgra.addItem(sve);

            for (VideoIgra vi : lista) {
                cmbVideoIgra.addItem(vi);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju video igara: " + ex.getMessage());
        }
    }

    private void ucitajComboZaposleni() {
        cmbZaposleni.removeAllItems();

        Zaposleni svi = new Zaposleni();
        cmbZaposleni.addItem(svi);

        Zaposleni z1 = new Zaposleni();
        z1.setIdZaposleni(1L);
        z1.setIme("Admin");
        z1.setPrezime("Admin");

        Zaposleni z2 = new Zaposleni();
        z2.setIdZaposleni(2L);
        z2.setIme("Marko");
        z2.setPrezime("Markovic");

        Zaposleni z3 = new Zaposleni();
        z3.setIdZaposleni(3L);
        z3.setIme("Jelena");
        z3.setPrezime("Jovanovic");

        cmbZaposleni.addItem(z1);
        cmbZaposleni.addItem(z2);
        cmbZaposleni.addItem(z3);
    }

}
