/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import communication.Communication;
import constants.Operacije;
import domain.KategorijaOsobe;
import domain.Osoba;
import form.model.ModelTabeleOsobe;
import form.osoba.IzmeniOsobu;
import form.osoba.KreirajOsobu;
import java.util.List;
import javax.swing.JOptionPane;
import transfer.Request;
import transfer.Response;
import transfer.ResponseStatus;

/**
 *
 * @author PC
 */
public class FrmOsoba extends javax.swing.JFrame {

    private final ModelTabeleOsobe model;

    public FrmOsoba() {
        initComponents();
        model = new ModelTabeleOsobe();
        tblOsobe.setModel(model);
        setLocationRelativeTo(null);
        ucitajKategorije();

    }
    
    private void ucitajKategorije() {

    cmbKategorijaOsobe.removeAllItems();

    cmbKategorijaOsobe.addItem(new KategorijaOsobe(null, "Sve"));

    cmbKategorijaOsobe.addItem(new KategorijaOsobe(1L, "Standard"));
    cmbKategorijaOsobe.addItem(new KategorijaOsobe(2L, "Student"));
    cmbKategorijaOsobe.addItem(new KategorijaOsobe(3L, "Premium"));
}

    private void ucitajSveOsobe() {
        try {
            Response response = Communication.getInstance().ucitajOsobe();

            if (response.getStatus() == ResponseStatus.SUCCESS) {
                java.util.List<Osoba> lista = (java.util.List<Osoba>) response.getPodatak();
                model.setLista(lista);
                JOptionPane.showMessageDialog(this, "Sistem je ucitao osobe.");
            } else {
                JOptionPane.showMessageDialog(this,
                        "Sistem ne moze da ucita osobe.\n"
                        + response.getException().getMessage());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da ucita osobe.\n" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOsobe = new javax.swing.JTable();
        btnKreiraj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnNazad = new javax.swing.JButton();
        btnPretrazi = new javax.swing.JButton();
        txtKriterijum = new javax.swing.JTextField();
        btnUcitaj = new javax.swing.JButton();
        cmbKategorijaOsobe = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma osoba");

        tblOsobe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOsobe);

        btnKreiraj.setText("Kreiraj");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel1.setText("Kriterijum pretrage: ");

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnUcitaj.setText("Učitaj");
        btnUcitaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbKategorijaOsobe, 0, 196, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKreiraj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNazad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUcitaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnPretrazi)
                    .addComponent(txtKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUcitaj)
                    .addComponent(cmbKategorijaOsobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKreiraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNazad))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        new KreirajOsobu().setVisible(true);
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void btnUcitajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajActionPerformed
        ucitajSveOsobe();
    }//GEN-LAST:event_btnUcitajActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
           try {

        String kriterijum = txtKriterijum.getText().trim();
        KategorijaOsobe kategorija = (KategorijaOsobe) cmbKategorijaOsobe.getSelectedItem();

        Osoba osoba = new Osoba();

        if (!kriterijum.isEmpty()) {
            osoba.setIme(kriterijum);
        }

        if (kategorija != null && kategorija.getIdKategorijaOsobe() != null) {
            osoba.setKategorijaOsobe(kategorija);
        }

        List<Osoba> lista = Communication.getInstance().pretraziOsobe(osoba);

        if(lista != null){
            JOptionPane.showMessageDialog(this, "Sistem je našao osobe po zadatim kriterijumima.");
        }
        ModelTabeleOsobe model = new ModelTabeleOsobe(lista);
        tblOsobe.setModel(model);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        try {
            int selectedRow = tblOsobe.getSelectedRow();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da učita osobu. Niste izabrali osobu.");
                return;
            }

            ModelTabeleOsobe model = (ModelTabeleOsobe) tblOsobe.getModel();
            Osoba osoba = model.getOsoba(selectedRow);

            JOptionPane.showMessageDialog(this, "Sistem je učitao osobu.");

            IzmeniOsobu fio = new IzmeniOsobu(osoba);
            fio.setLocationRelativeTo(this);
            fio.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri otvaranju forme za izmenu: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        try {
            int selectedRow = tblOsobe.getSelectedRow();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da obriše osobu. Niste izabrali osobu.");
                return;
            }

            ModelTabeleOsobe model = (ModelTabeleOsobe) tblOsobe.getModel();
            Osoba osoba = model.getOsoba(selectedRow);

            int potvrda = JOptionPane.showConfirmDialog(
                    this,
                    "Da li ste sigurni da želite da obrišete osobu?",
                    "Potvrda brisanja",
                    JOptionPane.YES_NO_OPTION
            );

            if (potvrda == JOptionPane.YES_OPTION) {

                Response response = Communication.getInstance().obrisiOsobu(osoba);

                if (response.getStatus() == ResponseStatus.SUCCESS) {

                    model.obrisiOsobu(selectedRow);

                    JOptionPane.showMessageDialog(this, "Sistem je obrisao osobu.");

                } else {
                    throw response.getException();
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da obriše osobu.\n" + ex.getMessage());
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnUcitaj;
    private javax.swing.JComboBox cmbKategorijaOsobe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOsobe;
    private javax.swing.JTextField txtKriterijum;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ModelTabeleOsobe mto = new ModelTabeleOsobe();
        tblOsobe.setModel(mto);
    }
}
