/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import communication.Communication;
import domain.VideoIgra;
import form.osoba.IzmeniOsobu;
import form.videoIgre.IzmeniVideoIgru;
import form.videoIgre.KreirajVideoIgre;
import java.util.List;
import javax.swing.JOptionPane;
import models.ModelTabeleVideoIgre;
import transfer.Response;
import transfer.ResponseStatus;

/**
 *
 * @author PC
 */
public class FrmVideoIgra extends javax.swing.JFrame {

    /**
     * Creates new form FrmVideoIgra
     */
    public FrmVideoIgra() {
        initComponents();
        setLocationRelativeTo(this);
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnObrisi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnNazad = new javax.swing.JButton();
        btnPretrazi = new javax.swing.JButton();
        txtKriterijum = new javax.swing.JTextField();
        btnUcitaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVideoIgra = new javax.swing.JTable();
        btnKreiraj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma Video Igra");

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel1.setText("Kriterijum pretrage: ");

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnUcitaj.setText("Učitaj");
        btnUcitaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajActionPerformed(evt);
            }
        });

        tblVideoIgra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVideoIgra);

        btnKreiraj.setText("Kreiraj");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 143, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKreiraj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNazad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUcitaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnPretrazi)
                    .addComponent(txtKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUcitaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKreiraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNazad))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        try {
            int selectedRow = tblVideoIgra.getSelectedRow();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da obriše video igru. Niste izabrali video igru.");
                return;
            }

            ModelTabeleVideoIgre model = (ModelTabeleVideoIgre) tblVideoIgra.getModel();
            VideoIgra videoIgra = model.vratiVideoIgru(selectedRow);

            int potvrda = JOptionPane.showConfirmDialog(
                    this,
                    "Da li ste sigurni da želite da obrišete video igru?",
                    "Potvrda brisanja",
                    JOptionPane.YES_NO_OPTION
            );

            if (potvrda == JOptionPane.YES_OPTION) {
                Response response = Communication.getInstance().obrisiVideoIgru(videoIgra);

                if (response.getStatus() == ResponseStatus.ERROR) {
                    throw response.getException();
                }

                model.obrisiVideoIgru(selectedRow);
                JOptionPane.showMessageDialog(this, "Sistem je obrisao video igru.");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da obriše video igru.\n" + ex.getMessage());
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        try {
            String kriterijum = txtKriterijum.getText().trim();

            if (kriterijum.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Unesite kriterijum za pretragu.");
                return;
            }

            VideoIgra vi = new VideoIgra();
            vi.setNaziv(kriterijum);

            List<VideoIgra> lista = Communication.getInstance().pretraziVideoIgre(vi);

            ModelTabeleVideoIgre model = (ModelTabeleVideoIgre) tblVideoIgra.getModel();
            model.setLista(lista);

            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe video igre po zadatoj vrednosti.");
            } else {
                JOptionPane.showMessageDialog(this, "Sistem je našao video igre po zadatoj vrednosti.");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri pretrazi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnUcitajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajActionPerformed
        try {
            Response response = Communication.getInstance().ucitajVideoIgre();

            if (response.getStatus() == ResponseStatus.ERROR) {
                throw response.getException();
            }

            List<VideoIgra> lista = (List<VideoIgra>) response.getPodatak();

            ModelTabeleVideoIgre model = (ModelTabeleVideoIgre) tblVideoIgra.getModel();
            model.setLista(lista);

            JOptionPane.showMessageDialog(this, "Sistem je učitao video igre.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita video igre.\n" + ex.getMessage());
        }
    }//GEN-LAST:event_btnUcitajActionPerformed

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        new KreirajVideoIgre().setVisible(true);
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            int selectedRow = tblVideoIgra.getSelectedRow();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da učita video igru. Niste izabrali video igru.");
                return;
            }

            ModelTabeleVideoIgre model = (ModelTabeleVideoIgre) tblVideoIgra.getModel();
            VideoIgra videoIgra = model.vratiVideoIgru(selectedRow);

            JOptionPane.showMessageDialog(this, "Sistem je učitao video igru.");

            IzmeniVideoIgru forma = new IzmeniVideoIgru(videoIgra);
            forma.setLocationRelativeTo(this);
            forma.setVisible(true);

            osveziTabeluVideoIgre();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri otvaranju forme za izmenu: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnUcitaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVideoIgra;
    private javax.swing.JTextField txtKriterijum;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ModelTabeleVideoIgre mtvi = new ModelTabeleVideoIgre();
        tblVideoIgra.setModel(mtvi);
    }

    private void osveziTabeluVideoIgre() {
        try {
            Response response = Communication.getInstance().ucitajVideoIgre();

            if (response.getStatus() == ResponseStatus.ERROR) {
                throw response.getException();
            }

            List<VideoIgra> lista = (List<VideoIgra>) response.getPodatak();

            ModelTabeleVideoIgre model = (ModelTabeleVideoIgre) tblVideoIgra.getModel();
            model.setLista(lista);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri osvežavanju tabele: " + ex.getMessage());
        }
    }
}
